### ISSUE TITLE
Should probably list this as a prerequisite

### ISSUE THREAD

**Issue by edale2** [RadzPrower/Zelda-3-Launcher#18]
.Net 7.0.4; 'Zelda 3 Launcher.exe' will not run until you have this installed.

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-7.0.4-windows-x64-installer?cid=getdotnetcore

**Comment by RadzPrower** [comment]
Did it prompt you to install the runtime when you attempted to run the application? Did it include a link to the runtime itself as well?

**Comment by edale2** [comment]
Yes it did.

**Comment by RadzPrower** [comment]
Since the framework requirement is presented by Windows and a link is provided to download the necessary framework, I would consider that issue covered as you do not need to independently download the framework but are instead directed to it via Windows itself and not all people will need to install the framework as it may already be installed.
